% Create a rectangularArray with patchMicrostrip element.`
% Generated by MATLAB(R) 9.9 and Antenna Toolbox 4.3.
% Generated on: 18-Jan-2021 10:13:25

%% Array Properties 
%Define Array
arrayObject = rectangularArray;

arrayObject.Size = [2  2];

%Define Array Elements
Element1 = patchMicrostrip;
arrayObject.Element = [Element1 ];

% Design array at frequency 2600000000Hz
arrayObject = design(arrayObject,2600000000,Element1);
%arrayObject Properties Changed
arrayObject.RowSpacing = 0.13274;
arrayObject.ColumnSpacing = 0.13834;

%Element1 Properties Changed
arrayObject.Element(1).GroundPlaneLength = 0.14813;
arrayObject.Element(1).GroundPlaneWidth = 0.15668;
% Update substrate properties 
arrayObject.Element(1).Substrate.Name = 'Air';
arrayObject.Element(1).Substrate.EpsilonR = 1;
arrayObject.Element(1).Substrate.LossTangent = 0;
arrayObject.Element(1).Substrate.Thickness = 0.00115304791538462;

%% Array Analysis 
% Show for rectangularArray
figure;
show(arrayObject) 
% Layout for rectangularArray
figure;
layout(arrayObject) 
% Pattern for rectangularArray
plotFrequency = 2600000000; Termination = 50;
figure;
pattern(arrayObject, plotFrequency,'Termination',Termination); 

